# Generated by Django 3.2 on 2021-05-06 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=50)),
                ('resource', models.TextField()),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='countbox',
        ),
    ]
