# Generated by Django 3.2 on 2021-05-16 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_auto_20210506_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
