# Generated by Django 3.2 on 2021-05-22 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0004_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
