# Generated by Django 3.2 on 2021-07-06 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0006_alter_blog_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='upchek',
            field=models.BooleanField(default=True),
        ),
    ]
