# Generated by Django 3.2 on 2021-07-06 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0007_blog_upchek'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='downchek',
            field=models.BooleanField(default=True),
        ),
    ]
