# Generated by Django 3.2 on 2021-07-07 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0009_auto_20210707_0523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='downchek',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='upchek',
            field=models.BooleanField(default=True),
        ),
    ]
